System hostname = darbs
Password for root = *
Setup a user = drew
Password for user = *
Public ssh key for user = none
Allow root ssh login = no
What timezone = US/Eastern
Which disk = sd0
Use (W)hole disk or (E)dit the MBR = W
Use (A)uto layout = A
URL to autopartitioning template = none
Location of sets = http
HTTP Server = cdn.openbsd.org
Server directory = pub/OpenBSD/7.8/amd64
Set name(s) = -game*.tgz -x*.tgz +xbase*.tgz +xshare*.tgz +xfont*.tgz +xserv*.tgz
Location of sets = done
